# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "pdf_extract"
  s.version = "0.2.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["noah pryor"]
  s.date = "2013-07-16"
  s.description = "description yo "
  s.email = "noah@noahpryor.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/pdf_extract.rb",
    "pdf_extract.gemspec",
    "test/helper.rb",
    "test/test_pdf_extract.rb"
  ]
  s.homepage = "http://github.com/noahpryor/pdf_extract"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "PDF extraction. Best with jRuby"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<tabula-extractor>, [">= 0"])
      s.add_runtime_dependency(%q<tesseract-ocr>, [">= 0"])
      s.add_runtime_dependency(%q<image_voodoo>, [">= 0"])
      s.add_runtime_dependency(%q<docsplit>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
    else
      s.add_dependency(%q<tabula-extractor>, [">= 0"])
      s.add_dependency(%q<tesseract-ocr>, [">= 0"])
      s.add_dependency(%q<image_voodoo>, [">= 0"])
      s.add_dependency(%q<docsplit>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    end
  else
    s.add_dependency(%q<tabula-extractor>, [">= 0"])
    s.add_dependency(%q<tesseract-ocr>, [">= 0"])
    s.add_dependency(%q<image_voodoo>, [">= 0"])
    s.add_dependency(%q<docsplit>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, [">= 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
  end
end

